import Head from "next/head";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { Auth } from "@supabase/auth-ui-react";
import { ThemeSupa } from "@supabase/auth-ui-shared";
import TodoList from "@/components/TodoList";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  return (
    <>
      <Head>
        <title>Reading book list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {!session ? (
          <div className="bg-gray-100 flex-col justify-center items-center">
            <div className="bg-gradient-to-br from-blue-600 to-cyan-300 flex flex-col justify-center items-center w-full py-8">
              <h1 className="text-2xl font-bold text-center text-white mb-4 italic">
                📝 My reading List
              </h1>
              <p className="text-white mb-10">
                Create account and save your reading books!
              </p>
              <div className="bg-white px-10 py-8 rounded-xl w-screen shadow-xl max-w-sm">
                <div className="space-y-2">
                  <h1 className="text-center text-black text-2xl font-semibold">
                    Login
                  </h1>
                  <Auth
                    supabaseClient={supabase}
                    appearance={{ theme: ThemeSupa }}
                  />
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="h-screen bg-gradient-to-br from-blue-600 to-cyan-300 flex flex-col justify-center items-center gap-10 w-full px-4 md:px-10">
            <div className="bg-white shadow-2xl rounded-2xl w-full max-w-md p-6">
              <TodoList session={session} />
            </div>
            <div>
              <button
                className="bg-black text-white px-4 py-2 rounded-r-md hover:bg-gray-600"
                onClick={async () => {
                  const { error } = await supabase.auth.signOut();
                  if (error) console.log("Error logging out:", error.message);
                }}
              >
                Logout
              </button>
            </div>
          </div>
        )}
      </div>
    </>
  );
}
