import Head from "next/head";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { Auth } from "@supabase/auth-ui-react";
import { ThemeSupa } from "@supabase/auth-ui-shared";
import TodoList from "@/components/TodoList";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {!session ? (
          <div className="bg-gray-100 h-screen flex-col justify-center items-center">
            <div className="h-screen bg-gradient-to-br from-blue-600 to-cyan-300 flex justify-center items-center w-full">
              <div className="bg-white px-10 py-8 rounded-xl w-screen shadow-xl max-w-sm">
                <div className="space-y-4">
                  <h1 className="text-center text-2xl font-semibold">Login</h1>
                  <Auth
                    supabaseClient={supabase}
                    appearance={{ theme: ThemeSupa }}
                  />
                </div>
              </div>
            </div>
          </div>
        ) : (
          <>
            <TodoList session={session} />
            <button
              className="btn btn-secondary"
              onClick={async () => {
                const { error } = await supabase.auth.signOut();
                if (error) console.log("Error logging out:", error.message);
              }}
            >
              Logout
            </button>
          </>
        )}
      </div>
    </>
  );
}
